AWSTemplateFormatVersion: 2010-09-09
Description: Template for the application instance role

Parameters:
  ImageId:
    Description: Id of the AMI with Application
    Type: AWS::EC2::Image::Id
  InstanceType:
    Description: Type of instance
    Type: String
    Default: t2.micro

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref  InstanceType
      IamInstanceProfile: !Ref  InstanceProfile
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref ApplicationSecurityGroup
          SubnetId: !ImportValue subnet-public-1-id
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum install -y httpd
          service httpd start
          chkconfig httpd on

          cat <<EOF> /var/www/html/index.html
          <html>
            <body>
              <h1> This is simple webpage hosted on EC2 instance</h1>
              <p> This is working! </p>
            </body>
          </html>
          EOF
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SecurityGroup for Application
      GroupName: application-sg
      VpcId: !ImportValue network-vpc-id
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The ID of the Instance
    Value: !Ref Instance
  InstanceIpAddress:
    Description: The instance IP address
    Value: !GetAtt Instance.PublicIp
  InstanceRole:
    Description: The instance role name
    Value: !Ref InstanceRole
